### ISSUE TITLE
Error w/ tools.jar

### ISSUE THREAD

**Issue by Arudarin** [iLexiconn/Qubble#1]
Apparently it stoppped somewhere in Java, so here it is:

> Microsoft Windows [Version 10.0.10586](c) 2015 Microsoft Corporation. All rights reserved.
> 
> C:\Users\koolb>cd C:\Users\koolb\Downloads\Qubble-master
> 
> C:\Users\koolb\Downloads\Qubble-master>gradle build
> Download http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/2.1-SNAPSHOT/ForgeGradle-2.1-20160401.201315-35.jar
> Download https://jcenter.bintray.com/com/github/tony19/named-regexp/0.2.3/named-regexp-0.2.3.jar
> Download https://jcenter.bintray.com/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar
> Download https://jcenter.bintray.com/com/nothome/javaxdelta/2.0.1/javaxdelta-2.0.1.jar
> Download https://jcenter.bintray.com/org/ow2/asm/asm-debug-all/5.0.3/asm-debug-all-5.0.3.jar
> Download https://jcenter.bintray.com/com/github/jponge/lzma-java/1.3/lzma-java-1.3.jar
> Download https://jcenter.bintray.com/com/github/abrarsyed/jastyle/jAstyle/1.3/jAstyle-1.3.jar
> Download https://jcenter.bintray.com/net/sf/trove4j/trove4j/2.1.0/trove4j-2.1.0.jar
> Download https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
> Download https://jcenter.bintray.com/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
> Download https://jcenter.bintray.com/com/google/guava/guava/18.0/guava-18.0.jar
> Download http://files.minecraftforge.net/maven/net/minecraftforge/fernflower/2.0-SNAPSHOT/fernflower-2.0-20151214.100946-17.jar
> Download https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.3.3/httpmime-4.3.3.jar
> Download https://jcenter.bintray.com/com/cloudbees/diff4j/1.1/diff4j-1.1.jar
> Download https://jcenter.bintray.com/trove/trove/1.0.2/trove-1.0.2.jar
> Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
> Download https://jcenter.bintray.com/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
> Download https://jcenter.bintray.com/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
> Download https://jcenter.bintray.com/org/jvnet/localizer/localizer/1.12/localizer-1.12.jar
> Download https://jcenter.bintray.com/commons-io/commons-io/1.4/commons-io-1.4.jar
> ###### 
> 
> ```
>      ForgeGradle 2.1-SNAPSHOT-da90449
> ```
> 
>   https://github.com/MinecraftForge/ForgeGradle
> ###### 
> 
> ```
>            Powered by MCP unknown
>          http://modcoderpack.com
>      by: Searge, ProfMobius, Fesh0r,
>      R4wk, ZeuX, IngisKahn, bspkrs
> ```
> ###### 
> 
> :deobfCompileDummyTask
> :getVersionJson
> :extractUserdev
> Download http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.9-12.16.0.1858-1.9/forge-1.9-12.16.0.1858-1.9.pom
> Download http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.9-12.16.0.1858-1.9/forge-1.9-12.16.0.1858-1.9-userdev.jar
> :downloadClient
> :downloadServer
> :splitServerJar
> :mergeJars
> :applyBinaryPatches
> :deobfProvidedDummyTask
> :extractDependencyATs SKIPPED
> :extractMcpData
> Download http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.9/mcp-1.9-srg.zip
> :extractMcpMappings
> Download http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_snapshot/20160401-1.9/mcp_snapshot-20160401-1.9.zip
> :genSrgs
> :deobfMcMCP
> Applying SpecialSource...
> Applying Exceptor...
> :sourceApiJava
> :compileApiJava UP-TO-DATE
> :processApiResources UP-TO-DATE
> :apiClasses UP-TO-DATE
> :sourceMainJava
> :compileJava
> Download http://maven.ilexiconn.net/net/ilexiconn/llibrary/1.3.0-1.9/llibrary-1.3.0-1.9.pom
> Download http://maven.ilexiconn.net/net/ilexiconn/llibrary/1.3.0-1.9/llibrary-1.3.0-1.9-dev.jar
> Download https://libraries.minecraft.net/oshi-project/oshi-core/1.1/oshi-core-1.1.pom
> Download https://repo1.maven.org/maven2/net/java/dev/jna/jna/3.4.0/jna-3.4.0.pom
> Download https://repo1.maven.org/maven2/net/java/dev/jna/platform/3.4.0/platform-3.4.0.pom
> Download https://libraries.minecraft.net/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.pom
> Download https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.pom
> Download https://repo1.maven.org/maven2/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.pom
> Download https://repo1.maven.org/maven2/io/netty/netty-parent/4.0.23.Final/netty-parent-4.0.23.Final.pom
> Download https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
> Download https://repo1.maven.org/maven2/com/google/guava/guava/17.0/guava-17.0.pom
> Download https://repo1.maven.org/maven2/com/google/guava/guava-parent/17.0/guava-parent-17.0.pom
> Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.pom
> Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/33/commons-parent-33.pom
> Download https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.pom
> Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/25/commons-parent-25.pom
> Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.9/commons-codec-1.9.pom
> Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/32/commons-parent-32.pom
> Download https://repo1.maven.org/maven2/net/java/jutils/jutils/1.0.0/jutils-1.0.0.pom
> Download https://libraries.minecraft.net/com/mojang/authlib/1.5.22/authlib-1.5.22.pom
> Download https://libraries.minecraft.net/com/mojang/realms/1.8.7/realms-1.8.7.pom
> Download https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.pom
> Download https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.pom
> Download https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.0-beta9/log4j-2.0-beta9.pom
> Download https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.pom
> Download https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.pom
> Download https://repo1.maven.org/maven2/jline/jline/2.13/jline-2.13.pom
> Download https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.pom
> Download https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.pom
> Download https://repo1.maven.org/maven2/com/typesafe/config/1.2.1/config-1.2.1.pom
> Download https://repo1.maven.org/maven2/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.pom
> Download https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.pom
> Download https://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.pom
> Download https://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.pom
> Download https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.pom
> Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.pom
> Download https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.pom
> Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.pom
> Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.pom
> Download https://libraries.minecraft.net/lzma/lzma/0.0.1/lzma-0.0.1.pom
> Download https://repo1.maven.org/maven2/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.pom
> Download https://libraries.minecraft.net/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.pom
> Download https://libraries.minecraft.net/com/paulscode/codecwav/20101023/codecwav-20101023.pom
> Download https://libraries.minecraft.net/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.pom
> Download https://libraries.minecraft.net/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.pom
> Download https://libraries.minecraft.net/com/paulscode/soundsystem/20120107/soundsystem-20120107.pom
> Download https://repo1.maven.org/maven2/net/java/jinput/jinput/2.0.5/jinput-2.0.5.pom
> Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.pom
> Download https://libraries.minecraft.net/org/lwjgl/lwjgl/parent/2.9.4-nightly-20150209/parent-2.9.4-nightly-20150209.pom
> Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.pom
> Download https://libraries.minecraft.net/java3d/vecmath/1.5.2/vecmath-1.5.2.pom
> Download https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.11/jansi-1.11.pom
> Download https://repo1.maven.org/maven2/org/fusesource/jansi/jansi-project/1.11/jansi-project-1.11.pom
> Download https://repo1.maven.org/maven2/org/fusesource/fusesource-pom/1.8/fusesource-pom-1.8.pom
> Download https://repo1.maven.org/maven2/org/scala-lang/scala-actors/2.11.0/scala-actors-2.11.0.pom
> Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5.pom
> Download https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.pom
> Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209.pom
> Download https://libraries.minecraft.net/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
> Download https://repo1.maven.org/maven2/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
> Download https://repo1.maven.org/maven2/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
> Download https://libraries.minecraft.net/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
> Download https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
> Download https://repo1.maven.org/maven2/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
> Download https://repo1.maven.org/maven2/com/google/guava/guava/17.0/guava-17.0.jar
> Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
> Download https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar
> Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
> Download https://repo1.maven.org/maven2/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
> Download https://libraries.minecraft.net/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
> Download https://libraries.minecraft.net/com/mojang/realms/1.8.7/realms-1.8.7.jar
> Download https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
> Download https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
> Download https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
> Download https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
> Download https://repo1.maven.org/maven2/jline/jline/2.13/jline-2.13.jar
> Download https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
> Download https://repo1.maven.org/maven2/com/typesafe/config/1.2.1/config-1.2.1.jar
> Download https://repo1.maven.org/maven2/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
> Download https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
> Download https://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
> Download https://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
> Download https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
> Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
> Download https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
> Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
> Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
> Download https://libraries.minecraft.net/lzma/lzma/0.0.1/lzma-0.0.1.jar
> Download https://repo1.maven.org/maven2/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
> Download https://libraries.minecraft.net/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
> Download https://libraries.minecraft.net/com/paulscode/codecwav/20101023/codecwav-20101023.jar
> Download https://libraries.minecraft.net/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
> Download https://libraries.minecraft.net/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
> Download https://libraries.minecraft.net/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
> Download https://repo1.maven.org/maven2/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
> Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
> Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
> Download https://libraries.minecraft.net/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
> Download https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.11/jansi-1.11.jar
> Download https://repo1.maven.org/maven2/org/scala-lang/scala-actors/2.11.0/scala-actors-2.11.0.jar
> Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
> Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
> Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
> Download https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
> Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
> Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
> Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar
> :compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':compileJava'.
>   
>   > Could not find tools.jar
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 1 mins 31.974 secs
> 
> C:\Users\koolb\Downloads\Qubble-master>gradle build --stacktrace
> ###### 
> 
> ```
>      ForgeGradle 2.1-SNAPSHOT-da90449
> ```
> 
>   https://github.com/MinecraftForge/ForgeGradle
> ###### 
> 
> ```
>            Powered by MCP unknown
>          http://modcoderpack.com
>      by: Searge, ProfMobius, Fesh0r,
>      R4wk, ZeuX, IngisKahn, bspkrs
> ```
> ###### 
> 
> :deobfCompileDummyTask
> :getVersionJson
> :extractUserdev UP-TO-DATE
> :downloadClient SKIPPED
> :downloadServer SKIPPED
> :splitServerJar SKIPPED
> :mergeJars SKIPPED
> :applyBinaryPatches SKIPPED
> :deobfProvidedDummyTask
> :extractDependencyATs SKIPPED
> :extractMcpData SKIPPED
> :extractMcpMappings
> :genSrgs SKIPPED
> :deobfMcMCP SKIPPED
> :sourceApiJava UP-TO-DATE
> :compileApiJava UP-TO-DATE
> :processApiResources UP-TO-DATE
> :apiClasses UP-TO-DATE
> :sourceMainJava UP-TO-DATE
> :compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':compileJava'.
>   
>   > Could not find tools.jar
> - Try:
>   Run with --info or --debug option to get more log output.
> - Exception is:
>   org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
>       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
>       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
>       at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
>       at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
>       at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
>       at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
>       at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
>       at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
>       at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>       at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
>       at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
>       at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
>       at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
>       at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
>       at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
>       at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
>       at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>       at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
>       at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
>       at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
>       at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>       at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
>       at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
>       at org.gradle.internal.Factories$1.create(Factories.java:22)
>       at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>       at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
>       at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
>       at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
>       at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
>       at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
>       at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>       at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
>       at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
>       at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
>       at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
>       at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
>       at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
>       at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
>       at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
>       at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
>       at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
>       at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
>       at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
>       at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
>       at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
>       at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
>       at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
>       at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
>       at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
>       at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
>       at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
>       at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
>       at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
>       at org.gradle.launcher.Main.doAction(Main.java:33)
>       at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
>       at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
>       at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
>       at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
>   Caused by: java.lang.IllegalStateException: Could not find tools.jar
>       at org.gradle.internal.jvm.JdkTools.<init>(JdkTools.java:57)
>       at org.gradle.internal.jvm.JdkTools.current(JdkTools.java:44)
>       at org.gradle.api.internal.tasks.compile.JavaHomeBasedJavaCompilerFactory$SystemJavaCompilerFactory.create(JavaHomeBasedJavaCompilerFactory.java:81)
>       at org.gradle.api.internal.tasks.compile.JavaHomeBasedJavaCompilerFactory$SystemJavaCompilerFactory.create(JavaHomeBasedJavaCompilerFactory.java:78)
>       at org.gradle.api.internal.tasks.compile.JavaHomeBasedJavaCompilerFactory.findCompiler(JavaHomeBasedJavaCompilerFactory.java:58)
>       at org.gradle.api.internal.tasks.compile.JavaHomeBasedJavaCompilerFactory.create(JavaHomeBasedJavaCompilerFactory.java:45)
>       at org.gradle.api.internal.tasks.compile.JavaHomeBasedJavaCompilerFactory.create(JavaHomeBasedJavaCompilerFactory.java:28)
>       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.createCompileTask(JdkJavaCompiler.java:56)
>       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
>       at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
>       at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
>       at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
>       at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
>       at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
>       at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
>       at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
>       at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
>       at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
>       at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
>       at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
>       at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
>       at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
>       at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
>       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
>       at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
>       ... 57 more
> 
> BUILD FAILED
> 
> Total time: 12.015 secs

**Comment by iLexiconn** [comment]
Do you have the Java JDK installed?

**Comment by Arudarin** [comment]
I believe I do, will check after school

**Comment by Arudarin** [comment]
Ok, so I did have JDK but it wasn't in my Java_Home enviroment I put it in and it works!
One question though, wheres the program that i use to open the program?

**Comment by Arudarin** [comment]
Ok, so I did have JDK but it wasn't in my Java_Home enviroment I put it in and it works!
One question though, wheres the program that i use to open the program

**Comment by Gegy** [comment]
It's a mod, like Tabula.
