### ISSUE TITLE
bad texture mapping when export to json

### ISSUE THREAD

**Issue by ghost** [iLexiconn/Qubble#2]
When import from tabula and then export to json, all texture mapping uv are set to:

```
      "uv": [
        0.0,
        0.0,
        1.0,
        1.0
      ],
```

version 1.10.2

https://github.com/iLexiconn/Qubble/blob/master/src/main/java/net/ilexiconn/qubble/server/model/exporter/JsonExporter.java#L76

**Comment by Gegy** [comment]
Yes, textures work differently in json and in regular entity models. It cannot be converted.

**Comment by ghost** [comment]
Block is shown in this editor ok, texturemap works, but it cannot be exported to json properly.

**Comment by Gegy** [comment]
Yes, you can't use regular textures on json.
